name: task_4
description: "Food Classification App using Camera and TFLite"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  permission_handler: ^12.0.1
  image_picker: ^1.0.7
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  image: ^4.1.7

  # TensorFlow Lite
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/food_101_model.tflite
    - assets/food_101_labels.txt
